daangn/codepocket

client/src/detail/Detail.tsx
client/src/detail/api.ts
client/src/detail/components/Sandpack/index.tsx
client/src/detail/components/SandpackLoader/index.tsx
client/src/detail/hooks/useCode.ts
client/src/pocket/components/CodeList/index.tsx
client/src/pocket/components/Codeblock/index.tsx
client/src/routes.ts
core/server/src/getCode.ts
core/server/src/index.ts
core/server/src/types/index.ts
schema/json/getCodeRequest.json
schema/json/getCodeResponse.json
schema/json/getCodesResponse.json
server/src/dbModule/code.ts
server/src/router.ts
server/src/utils/responseHandler.ts

closes #65 
- 변경된 부분이 좀 많습니당
- getCode api 추가 구현
- schema / server / core-server 로직 수정
- detail페이지 라우팅 경로 변경
- useCode를 다시 안으로 불러들여왔어요
- 대면리뷰 예정

client detail routing 경로 변경

---

.github/workflows/test.yml
cli/lib/__mocks__/handlers.ts
cli/lib/api.ts
cli/lib/command/delete.ts
cli/lib/command/list.ts
cli/lib/command/pull.ts
cli/lib/command/push.ts
cli/lib/env.ts
cli/lib/utils.ts
cli/package.json

closes #20 
- server주소 지정하지 않으면 default path로 날라간다
- default url 도입으로 util함수 하나 없앴어요

change cli dev path변경

---

client/src/detail/Detail.tsx
package.json

closes #76 
- 매우 간단한 한 줄 수정입니다

detail 페이지 익명 ui도입(간단)

---

core/server/src/pushCode.ts
server/src/dbModule/code.ts
server/src/router.ts
server/src/utils/responseHandler.ts

closes #81 
- pushCode시에 isAnonymous가 true라면 기존에 있는 코드들중에서 코드이름이 중복되는게 있는지 체크해주는 로직을 추가해주었어요

server pushcode 로직 수정

---

client/src/auth/hooks/useCustomAuth0.ts

(client/external) email domain 검사 안하도록 처리

---

cli/lib/api.ts
cli/lib/env.ts
cli/package.json
server/src/config.ts
server/src/router.ts
server/src/utils/env.ts

closes #84 
- 슬랙 없을 경우 처리
- cli 주소 처리

deploy 에러 수정

---

cli/lib/config.ts
cli/lib/index.ts
cli/package.json
client/package.json
core/server/package.json
server/package.json
server/src/dbModule/code.ts
yarn.lock

closes #95 
- cli, server에서 로직 수정

deploy 에러 수정(#95)

---

server/src/dbModule/code.ts

closes #105 
- 간단히 return시에 조건문을 추가해주었어요

code정보 가져올 때 anonymous 적용

---

.github/workflows/deploy-codepocket-external.yml
client/src/auth/Auth.tsx

(chore/client) Authpage email 확인 로직 수정

---

.github/workflows/deploy-codepocket-external.yml

(common) cloudflare CD paths 수정

---

Dockerfile.kontrol
server/package.json

closes #132 
- 서버에 start script를 추가하였어요.
- dockerfile.kontrol에서 start를 실행해요

start script 서버에 추가

---

client/src/__mocks__/handlers.ts

chore: 잘못된 환경변수 수정

---

.github/workflows/deploy-codepocket-external.yml

[common] codepocket-external -> codepocket으로 도메인 변경

---

client/index.html
client/package.json
client/src/auth/style.css.ts
client/src/main.tsx
yarn.lock

closes #128 
[애셔가 올려준 해당 페이지](https://github.com/daangn/seed-design/tree/project-setup)보고 시드 디자인 적용했어요.
루트 엘리먼트 (`html`) 태그에 어트리뷰트들을 지정해줘야 정상작동 하더라구요

seed-design/design-token 적용

---

core/server/src/deleteStory.ts
core/server/src/index.ts
schema/json/deleteStoryRequest.json
schema/json/deleteStoryResponse.json
server/src/dbModule/code.ts
server/src/dbModule/story.ts
server/src/router.ts
server/src/utils/responseHandler.ts

closes #146
- 스토리 삭제 api 구현
- ㅅ토리 삭제 schema구현

스토리 삭제 api 및 스키마 구현

---

.eslintrc.json
client/src/auth/hooks/useCreateUser.ts
client/src/shared/utils/localStorage.ts
core/server/src/createUser.ts
core/server/src/types/index.ts
schema/json/createUserResponse.json
server/src/dbModule/user.ts
server/src/router.ts

로그인 시 userId 받도록 추가

---

core/server/src/index.ts
core/server/src/types/index.ts
core/server/src/updateStory.ts
schema/json/updateStoryRequest.json
schema/json/updateStoryResponse.json
server/src/dbModule/story.ts
server/src/router.ts
server/src/utils/responseHandler.ts

closes #155 
- schema구현
- server api 구현

story 수정하기 api 로직 구현

---

server/API.md
server/src/router.ts

closes #174 
- 현재까지 나온 server api에 대해 문서를 작성하였어요
- 웹/cli중 어느곳에서 사용중인지, 어떤 스키마를 쓰고 있는지 특이사항에 적어놓았어요
- 적고보니 하나의 api를 웹과 cli에서 쓰고 있는 부분이 pushCode밖에 없더군요(곧 바뀔)
- 헷갈릴 수도 있을텐데 보시다가 이상한 부분 있으면 말씀해주시면 될 것 같아요

server api 문서 작성

---

client/src/detail/Detail.tsx
client/src/detail/components/ErrorModal/index.tsx
client/src/detail/components/ErrorModal/style.css.ts
client/src/detail/components/Sandpack/index.tsx
client/src/detail/components/StoryConfirmModal/index.tsx
client/src/detail/components/StoryConfirmModal/style.css.ts
client/src/detail/hooks/useCreateStory.ts
client/src/detail/hooks/useStory.ts
client/src/detail/hooks/useStoryNames.ts
client/src/detail/style.css.ts
client/src/pocket/components/Codeblock/index.tsx
client/src/shared/contexts/GlobalModal.tsx
client/src/shared/contexts/ModalContext.tsx
client/src/shared/hooks/useCode.ts
client/src/shared/utils/Transition.tsx
core/server/src/createCode.ts
core/server/src/updateCode.ts
server/src/dbModule/code.ts
server/src/router.ts

closes #188 
- 기존에 분리해서 사용하던 거 통합했어요

client detail modal context사용으로 통합

---

client/src/auth/hooks/useCustomAuth0.ts

당근 페이 도메인 추가

---

.github/workflows/test.yml
client/src/detail/components/StoryNameList/index.tsx
core/server/src/createStory.ts
core/server/src/getStoryNames.ts
core/server/src/types/index.ts
schema/json/getStoryNamesResponse.json
server/API.md
server/src/dbModule/story.ts
server/src/schema.ts

closes #191 
- story에 userId속성을 넣어주었어요.
- 이제 스토리를 작성한 주인만 수정/삭제가 가능해요
- 스토리 수정/삭제 모달의 메세지를 상황에 따라 달리 보여줘요
- 리뷰후 변경사항이 딱히 없다면 머지해주세요
- 머지된 후 kontrol배포를 다시해주세요
- 테스트가 왜 통과하지 않는지 모르겠어요. 권한이 없어서 확인이 안되는데, 어드민 권한 줄 수 있는지 확인부탁드려요

story에 userId부여

---

client/src/pocket/components/Codeblock/index.tsx
client/src/pocket/components/Codeblock/style.css.ts

overflow text auto 처리

---

server/src/dbModule/code.ts
server/src/dbModule/index.ts
server/src/dbModule/story.ts
server/src/dbModule/user.ts
server/src/router.ts
server/src/utils/responseHandler.ts

closes #179 
기존에 혼란하던 서버의 모듈들을 한 번 정리했어요.
생각보다 중복이 많지는 않더라구요. 일단 일차적으로 한 번 정리했어요.
dbModules가 커링으로 되어있는데 server를 모두 첫 번째 인자로 받아요. 그거를 dbModules/index.ts파일을 통해서 중복이 없도록 수정했어요

server db modules 리팩토링

---

server/package.json
server/src/index.ts
yarn.lock

closes #182 
지원하는 라이브러리가 있어 편하게 적용가능하네요. 하지만 내부는 비어있어 내용은 [문서](https://github.com/fastify/fastify-swagger)를 보고 추가해야할 것 같긴해요.
서버 주소 뒤에 `/docs`를 붙히면 들어갈 수 있답니당

@fastify/swagger설치 및 적용
